### ISSUE TITLE
Feature request: Adhere to Graphql spec

### ISSUE THREAD

**Issue by BartOtten** [allegro/ecto-cursor-based-stream#6]
Cursor based pagination is also used by many Graphql api’s. So I would like to propose to adhere to their options and return values. As example:

- before_cursor
- has_next_page
- has_previous_page

https://graphql.org/learn/pagination/

Is this something that might be of interest?

**Comment by jtomaszewski** [comment]
To do this, we would have to abandon the interface that resembles `.stream() :: [Row.t()]` , and instead do something like `.pages() :: [Page.t()]` or `.paginate() :: Page.t()` (maybe similarly to how [scrinever](https://github.com/drewolson/scrivener_ecto) is currently doing it, but of course we'd do it with cursor-based pagination instead of offset-based).

However, this sounds like something what [paginator](https://github.com/duffelhq/paginator) is already doing. Would using it be sufficient in your case?

**Comment by BartOtten** [comment]
It was merely a suggestion as I read about this project in a blog post; didn't know of Paginator. Now I wonder what benefits of both projects are. Paginator can return the meta, what benefit does this lib provide? 

Maybe an entry in the README can make this clear or both projects can combine their strength?

**Comment by jtomaszewski** [comment]
> It was merely a suggestion as I read about this project in a blog post; didn't know of Paginator. 

Sadly, me neither. I learned about it only a few days ago after this whole library had been published already.

> Maybe an entry in the README can make this clear or both projects can combine their strength?

[I asked them](https://github.com/duffelhq/paginator/issues/183) if they would be interested in having a similar `.stream()` function. Currently that's the only thing from here that paginator doesn't have. We'll see if they'd be open to it.
